### ISSUE TITLE
Does not render last H3

### ISSUE THREAD

**Issue by newvicklee** [theisel/astro-toc#3]
## Describe the bug

Here's an example list of headers in markdown:
```
## hello
## world
### a. test
### b. this
```

The H3 header `### b. this` does not show up.

## Debugging

The culprit are lines 39-40 of `TOC.astro`:

```js
const nextHeading = headings[idx + 1]
const subHeadings = toc.slice((toc as any).indexOf(it) + 1, (toc as any).indexOf(nextHeading));
```

If we're iterating through all the headings with `depth=2`, then when we're at the last element `## world`, there is no more heading after it. This causes `nextHeading` to be undefined.

So when calculating `subHeadings`, the second argument passed into slice is `toc.indexOf(undefined)` which is `-1`. This means that the slice will only return the next item, and not retrieve the last item. 

## Proposed fix

```js
const nextHeading = headings[idx + 1];
let subHeadings = toc.slice((toc as any).indexOf(it) + 1, (toc as any).indexOf(nextHeading));
if (!nextHeading) subHeadings = toc.slice((toc as any).indexOf(it) + 1);
```

If `nextHeading` is undefined, then `subHeadings` will just grab the remainder of `toc`.

**Comment by theisel** [comment]
Thanks @newvicklee. I'll look into this.
