### ISSUE TITLE
Doesn't render without tag of depth 1

### ISSUE THREAD

**Issue by bennycode** [theisel/astro-toc#6]
I am using `<TOC />` but I noticed that it does not render when the `toc` only includes h2 and h3 headings. Currently, I am quickfixing it by manually pushing an h1 heading (`depth: 1`) into my toc:

```ts
toc.unshift({
  title: 'Glossary',
  depth: 1,
  url: '',
});
```

Would it be possible to render a TOC even when there is no h1?

**Comment by theisel** [comment]
@bennycode thanks for posting the issue. It needs a fix, leave it with me.

**Comment by bennycode** [comment]
Thanks for looking into it! 

I noticed that issue when generating the TOC for my [TypeScript glossary](https://typescript.tv/glossary/). To make it work, I am pushing a depth 1 title into it which then generates another ordering with "1.":

<img width="298" alt="image" src="https://github.com/theisel/astro-toc/assets/469989/ce38e862-b0ef-46cf-b38e-862ee5a9abef">

**Comment by theisel** [comment]
@bennycode Have you tried passing in `depth` prop? `depth` prop is used with recursive call to TOC. If your toc payload starts with depth 2 use 2. This may be a better quick fix. I'll wait to hear from you before I publish the next version.

```js
<TOC toc={toc} depth={2} as="number" />
```

**Comment by bennycode** [comment]
Thank you for this hint! Passing in `depth={2}` helped. 👍
